# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=60)),
                ('car_type', models.CharField(max_length=10)),
                ('frame', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgressModel',
            fields=[
                ('file_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('progress', models.IntegerField()),
                ('max_frame', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('unique_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('state_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
